default_platform :ios

platform :ios do
  workspace = 'XCTestHTMLReport.xcworkspace'
  scheme = 'XCTestHTMLReport'
  archive_path = 'XCTestHTMLReport.xcarchive'

  before_all do
  end

  desc "Build app for InHouse"
  lane :build do
  end

  desc "Build app for InHouse"
  lane :archive do
    xcodebuild(
      archive: true,
      archive_path: archive_path,
      scheme: scheme,
      workspace: workspace,
    )    
  end

  desc "Build sim app"
  lane :build_sim do
  end

  desc "Run test!"
  lane :test do
    sh('cd ..; thor test:once')
  end

  after_all do |lane, options|
  end

  error do |lane, exception, options|
  end
end
